---
title: 我的国家2.0指南
hero_image: images/banner.png
description: 进一步提升您的网站设计技能！
theme: 红色
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html/css
site_areas: coderdojo, projects
hardware: ''
software: html/css
version: 1
last_tested: 2017年1月1日
steps:
  - 
    title: 介绍
  - 
    title: 调整好设置
  - 
    title: 所有颜色！
  - 
    title: 组织您的页面
    completion:
      - engaged
  - 
    title: 设计一些主题
  - 
    title: 单个样式
  - 
    title: 查看其他网站上的代码！
  - 
    title: 自动调整大小
  - 
    title: 动画
  - 
    title: 教 Tito 翻转！
    completion:
      - internal
