---
title: Guide to my country 2.0
hero_image: images/banner.png
description: Uzmite svoje vještine dizajna web-lokacije dalje!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projekti
hardware: ''
software: html-css-javascript
version: 1
last_tested: 2017-01-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Getting set up
  - 
    title: All the colours!
  - 
    title: Organising your page
    completion:
      - engaged
  - 
    title: Design some themes
  - 
    title: Individual style
  - 
    title: See the code on other websites!
  - 
    title: Automatically adjust the size
  - 
    title: Animation
  - 
    title: Teach Tito to roll over!
    completion:
      - internal
