---
title: Zwischen HTML / CSS Sushi Karten
hero_image: Bilder / Banner.png
description: Nimm deine Designfähigkeiten auf der Webseite mit!
theme: rot
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: HTML-CSS-Javascript
site_areas: Coderdojo, Projekte
hardware: ''
software: HTML-CSS-Javascript
version: 1
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Einrichten eingerichtet
  - 
    title: Alle Farben!
  - 
    title: Organisieren Sie Ihre Seite
  - 
    title: Entwerfen Sie einige Themen
  - 
    title: Individueller Stil
  - 
    title: Siehe den Code auf anderen Websites!
  - 
    title: Passen Sie die Größe automatisch an
  - 
    title: Animation
  - 
    title: Bringe Tito bei, sich umzudrehen!
