---
title: Hărți intermediare HTML / CSS Sushi
hero_image: images / banner.png
description: Luați-vă abilitățile de design de site web în continuare!
theme: roșu
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-JavaScript
site_areas: coderdojo, proiecte
hardware: ''
software: html-css-JavaScript
version: 1
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Ce vei avea nevoie
  - 
    title: Se pregătește
  - 
    title: Toate culorile!
  - 
    title: Organizarea paginii dvs.
  - 
    title: Proiectați câteva teme
  - 
    title: Stilul individual
  - 
    title: Vezi codul de pe alte site-uri!
  - 
    title: Reglați automat dimensiunea
  - 
    title: Animaţie
  - 
    title: Învățați-l pe Tito să se răcească!
