---
title: Guia para o meu país 2.0
hero_image: images/banner.png
description: Melhore suas habilidades em criar página da web ainda mais!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 1
last_tested: 01/01/2017
steps:
- title: Introdução
  completion: engaged
- title: Preparando
- title: Todas as cores!
- title: Organizando sua página
- title: Crie alguns temas
- title: Estilo individual
- title: Veja o código em outros sites!
- title: Ajuste automaticamente o tamanho
- title: Animação
  completion: internal
- title: Ensine Tito a rolar!
