---
title: 아일랜드 여행 가이드 2.0
hero_image: images/banner.png
description: 본인의 웹 사이트 디자인 기술을 더 발전시켜 보세요!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 1
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 설정하기
  - 
    title: 모든 색상!
  - 
    title: 내 페이지 구성하기
    completion:
      - engaged
  - 
    title: 몇가지 테마의 디자인
  - 
    title: 개별 레이아웃
  - 
    title: 다른 웹 사이트에서 코드를 확인하세요!
  - 
    title: 크기 자동 조정
  - 
    title: 애니메이션
  - 
    title: Tito가 롤오버하도록 가르쳐주세요!
    completion:
      - internal
